name: Release app

on:
    repository_dispatch:
      types: [ release-app-to-prod ] 
    workflow_dispatch:

jobs:
    deploy-app:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Create release branch
              uses: peterjgrainger/action-create-branch@v2.3.0
              if: github.event_name == 'repository_dispatch' && github.event.action == 'release-app-to-prod'
              env:
                GITHUB_TOKEN: ${{ secrets.REPO_ACCESS }}
              with:
                branch: release/app-${{ github.run_number }}
              
            - name: Deploy app
              run: echo "App deployed successfully!!"
  
